"""new fields in user model

Revision ID: 371d64c95f37
Revises: 76f621c55b9c
Create Date: 2021-03-24 16:32:30.599171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371d64c95f37'
down_revision = '76f621c55b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
